name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v2

      
      # Log in to Render (Replace with your API key from Render)
      - name: Deploy to Render
        
        env:
        email: ${{ secrets.RENDER_EMAIL }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_NAME: ${{ secrets.RENDER_SERVICE_NAME }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d ''